### ISSUE TITLE
Generating Flight Logs

### ISSUE THREAD

**Issue by czadraOA** [dbaldwin/SnotBot#4]
What information do we want to log? Can it still be compatible with Airdata?

**Comment by dbaldwin** [comment]
@czadraOA what process do you use to upload the flight logs? Do you use a manual process as described here?

https://app.airdata.com/main?a=upload#manualupload

I ask because I'm wondering if the following will be sufficient if we enable it in the SB app:

https://developer.dji.com/iframe/mobile-sdk-doc/android/reference/dji/sdk/sdkmanager/DJISDKManager.html#archiveLogs(dji.common.util.DJICommonCallbacks.DJICompletionCallback)

**Comment by czadraOA** [comment]
@dbaldwin I've been using their app HDSync that automatically finds DJI logs on the Crystal Sky and uploads them. It might still work with our app if we use archiveLogs() since it seems it will format it all the same, I know it works with other third party apps like Litchi and Dronedeploy, but it's also easy enough to do it manually.

**Comment by czadraOA** [comment]
I think it's takeoff and landing but as in motors starting up and motors stopping. I'll upload an example log file to Slack. We actually didn't really use the logs until I got here and signed us up for Airdata, now Iain can't get enough! Definitely will need logs on expeditions now mostly for generating reports for publishing later, but it's also very useful for tracking maintenance

**Comment by dbaldwin** [comment]
Logging some observations here. Apparently log files are stored by the SDK by default. I verified by adding this code after the product is connected:

Log.v(TAG, DJISDKManager.getInstance().getLogPath());

Which gives me:

/mnt/internal_sd/DJI/com.unmannedairlines.snotbot/FlightRecord

I can use adb to list the files:

adb ls /mnt/internal_sd/DJI/com.unmannedairlines.snotbot/FlightRecord

Using adb I can pull the log file from the device to my local machine:

and pull the most recent:

adb pull /mnt/internal_sd/DJI/com.unmannedairlines.snotbot/FlightRecord/DJIFlightRecord_2018-11-05_[17-28-46].txt ~/Desktop

I'm attaching the file but it appears to be encrypted. @czadraOA can you take a look and let me know if this is useable by Airdata or do we need to decrypt it somehow? 

[DJIFlightRecord_2018-11-05_[17-28-46].txt](https://github.com/dbaldwin/SnotBot/files/2576953/DJIFlightRecord_2018-11-05_.17-28-46.txt)

**Comment by czadraOA** [comment]
All looks great. Airdata decrypts the logs when we upload them. Are those logs on the internal_sd of the CrystalSky?

**Comment by dbaldwin** [comment]
Cool. I'm going to close this for now. We can always come back later if there is something more we want to do.
