### ISSUE TITLE
Camera Focus

### ISSUE THREAD

**Issue by czadraOA** [dbaldwin/SnotBot#8]
Add tap to focus to work with Inspire 1 w/ X5 and Inspire 2 w/ X4S

**Comment by dbaldwin** [comment]
It looks like we have the necessary widget in our code:

https://github.com/dbaldwin/SnotBot/blob/master/app/src/main/res/layout/activity_main.xml#L23

and this is how it should behave:

https://developer.dji.com/api-reference/android-uilib-api/Widgets/FPVOverlayWidget.html

But it obviously doesn't. I'm going to look into this some more to see what's going on.
